name: deploy adv
on: [workflow_dispatch]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: supnobita/ssh-action@master
              with:
                  host: 54.169.185.39
                  username: ubuntu
                  key: ${{ secrets.ADV_DEV_SECRET }}
                  port: 22
                  envs: GITHUB_RUN_NUMBER
                  script: |
                      cd code/
                      rm -rf adv/
                      git clone https://${{ secrets.ADV_DEV_TOKEN_SSH }}@github.com/zunohan/adv.git
                      cd adv
                      docker build -t adv:$GITHUB_RUN_NUMBER .
                      docker stop adv || echo "OK"
                      docker rm adv || echo "OK"
                      docker run --name adv -p 6969:6969 adv:$GITHUB_RUN_NUMBER
